### ISSUE TITLE
Error in Text Mining: Error in elem$content[, m] : incorrect number of dimensions

### ISSUE THREAD

**Issue by TheOne000** [kwartler/ODSC_Workshop#1]
I am doing text mining. When import data to VCorpus(), there is an error message.

    Error in elem$content[, m] : incorrect number of dimensions
How can I solve it? Thank you very much
 
My CSV file is in this format
![image](https://user-images.githubusercontent.com/26129695/28470912-34249bc2-6e33-11e7-98d7-58962c5d2c72.png)

  
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
      # 2.) Build a corpus: a collection of statements#  
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

     # Get the current working directoty 

     getwd() 

     file <- "C:\\Users\\Boon\\Desktop\\Dissertation\\F1\\f.csv"
     options(stringsAsFactors = FALSE)

     doc<-read.csv(file, header=TRUE)

      custom.reader<-readTabular(mapping = list(content="Statement_1", id="id"))
      corpus <-VCorpus(DataframeSource(doc),readerControl=list(reader=custom.reader))

**Comment by kwartler** [comment]
My first thought is that the read tabular code is looking for a column called Id. In fact you actually could probably use VectorSource instead because you have a singular vector of text not a data frame.

**Comment by TheOne000** [comment]
Hi Ted,
  Thank  you very much for your reply.  May I ask a little bit more?  In my csv file, each row is 1 document.
Thus, I think VCorpus should return  3 Documents in my case.  Do you have comments on this,please?
Regards

**Comment by kwartler** [comment]
Ok try this.  You should have 3 documents in your corpus.  I provided a simple VectorSource version and a DF version.  When you call the `corpus` and `corpus.df` objects not the differences.  Your numerics preceding the text will be considered part of the document text not an id in your example so maybe use a string split to create a numeric ID vector?
```
library(tm)

v1<-c('123 hello','345 I am a buy','434 Are you ok')

v2<-c(123,345,434)
v3<-c('hello','I am a boy','are you ok')
df<-data.frame(id=v1,Statement_1=v3)


corpus<-VCorpus(VectorSource(v1))
corpus
corpus[[1]]
corpus[[1]]$content

custom.reader<-readTabular(mapping = list(content="Statement_1", id="id"))
corpus.df <-VCorpus(DataframeSource(df),readerControl=list(reader=custom.reader))
corpus.df
corpus.df[[1]]
corpus.df[[1]]$content
```

**Comment by TheOne000** [comment]
Thank you very much, Ted!  It does work. I try studying your code and rewrite it by myself again.
really appreciated for your efforts!
Regards
Bun

**Comment by kwartler** [comment]
No worries. Hit me up if you need help if get my book on amazon :) for more text mining code and case studies.

**Comment by TheOne000** [comment]
Thank you Ted. :D 
One more thing, suppose I have the term-document matrix, how can I transform the matrix into the term-document matrix with TF-IDF?
Can I use this code?

terms <-DocumentTermMatrix(corpus,control = list(weighting = function(x) weightTfIdf(x, normalize = FALSE)))

Thank you!

**Comment by kwartler** [comment]
Check this out. 

https://stackoverflow.com/questions/14820590/trying-to-get-tf-idf-weighting-working-in-r

That should answer it. Tfidf is recognized within the list.

Ted
